# remember "rake asset:packager:build_all"

---
javascripts:
- base:
  - jquery
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jHtmlArea
  - jquery.autocomplete
  - jquery.autoSuggest
  - jquery.notifyBar
  - jquery.marquee
  - jquery.scroll
  - jquery.ui.sortable
  - jquery.cookie
  - jquery.effects.core
  - jquery.effects.bounce
  - showdown
  - highlight/prettify
  - components/search
  - application
  - modules/sessions
  - modules/index_item
  - modules/retag
  - modules/new_item
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/tags_item
  - modules/members
  - modules/move_group
  - modules/editor


- show:
  - modules/single/item
  - jquery.autovideo
  - modules/show_item

- login:
  - openid/js/jquery.openid.min



stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - prettify
  - ../javascripts/openid/css/style

